### ISSUE TITLE
My pesterchum client says there's an python error in main script

### ISSUE THREAD

**Issue by Russianboy102** [Dpeta/pesterchum-alt-servers#57] opened 2021-08-23 16:58 UTC
![IMG_20210823_194030](https://user-images.githubusercontent.com/89410461/130486891-c0478ab6-e704-4179-9b8a-754ae4db93a8.jpg)
I don't know how to fix it and people in the mspfa discord said to leave a tip to you about this.

**Comment by Dpeta** [comment] 2021-08-24 14:33
Hmm, that's not a lot to go off óvò
Are you sure you extracted the zipfile? :?c That's certainly something obvious that can cause an error like this

**Comment by Russianboy102** [comment] 2021-08-24 17:22
I obviously did, i know that you have to extract a zip file before using it.

**Comment by Dpeta** [comment] 2021-08-24 21:33
Ruling out obvious things is important, it wouldn't have been nearly the first time someone forgot to.

I was able to reproduce the error by emulating 32-bit Windows 7 though:
![Screenshot_20210824_212706](https://user-images.githubusercontent.com/69427753/130692158-64868410-46bb-4aae-a917-72d4822efc5a.png)
I'm pretty sure it's because cx_freeze packaged the 64-bit version of Microsoft's CRT with this build instead of the 32-bit version, which is required to run Python on Windows 7, so this build probably won't work on (32-bit) Windows 7.

It should be fixed on [the version I just put up](https://github.com/Dpeta/pesterchum-alt-servers/releases/tag/v2.1.3.1), it's working now for me at least.
![Screenshot_20210824_224234](https://user-images.githubusercontent.com/69427753/130692862-653b04a8-f8de-48b5-b3f3-57d5179a4de3.png)

**Comment by Russianboy102** [comment] 2021-08-24 22:22
Ok I'll be sure to download it soon, and thank you for this. Like i am actually thankful for you helping me.

**Comment by Dpeta** [comment] 2021-08-24 22:51
Np!! 🐱👍

**Closed** 2021-09-18 10:50 UTC
