### ISSUE TITLE
Text in message box is white and unreadable

### ISSUE THREAD

**Issue by LithRakoon** [Dpeta/pesterchum-alt-servers#78] opened 2022-04-21 19:12 UTC
Hello!

when pestering someone the text of the message box is unreadable because its white
this seems to a linux bug as my friend using windows does not have this problem
![image](https://user-images.githubusercontent.com/41258148/164535071-499faada-899f-4baf-879d-9187b45ad19e.png)
system: linux fedora 35
windowing: X11
version: PesterchumAlt.-2.2.2-linux64-glibc2.31

**Comment by Dpeta** [comment] 2022-04-22 11:35
This seems to happen on mac too, people have reported it before. Could you try running the source version? fe53f1bf7b2590e49c200adf1fc552c0ea6ec354 was an attempt to fix this.

**Comment by LithRakoon** [comment] 2022-04-22 11:39
source has fixed the issue!
unrelated to the current problem did does happen to me on source
![image](https://user-images.githubusercontent.com/41258148/164707526-b718baf9-4739-4943-8498-9d21c710e173.png)

**Comment by Dpeta** [comment] 2022-04-22 12:14
I think that's a Wayland issue, I've had that happen too, not sure what the cause is rn :"3
Seems like there's some notable differences with how Qt work on x11 vs Wayland, there's probably some stuff to be done to make Pesterchum function normally with it </3

**Comment by Dpeta** [comment] 2022-05-04 20:56
This should also be fixed now since [8a3ebd1](https://github.com/Dpeta/pesterchum-alt-servers/commit/8a3ebd1d3f54c38dd38d5313585424080dee9d87), Wayland doesn't support explicitly setting position with setPosition, so things broke when trying to drag the window.

> [on some platforms such as Wayland, setPosition is not supported, so this is the only way the application can influence its position.](https://doc.qt.io/qt-5/qwindow.html#startSystemMove)

**Closed by Dpeta** 2022-05-04 20:56 UTC
Labels: bug
