### ISSUE TITLE
hihi help pls 

### ISSUE THREAD

**Issue by gardenSnotstic** [Dpeta/pesterchum-alt-servers#17] opened 2021-02-11 20:11 UTC
my pesterchum fully just wont open and it keepss showing this popup 
![2021-02-11](https://user-images.githubusercontent.com/78932331/107692741-d9bc4d00-6c72-11eb-9909-90480ce68a2b.png)
ive redowloaded it multiple times and i read ur othr comment for someone else abt the same issue but i geniuely have no idea how to fix this or backup a file:(

**Comment by Dpeta** [comment] 2021-02-14 01:23
Alright, so, I've tried to make it so it (hopefully) won't crash anymore when it fails to open the default profile in the newest release, could you try and see if it works for you?

**Comment by Dpeta** [comment] 2021-03-11 23:41
The issue is somewhat fixed now.

**Closed by Dpeta** 2021-03-11 23:41 UTC
Labels: bug
